import { Route } from '../types'

export const ODESSA_DEFAULT_ROUTES: Route[] = [
  // --- ТРАМВАЇ ---
  {
    id: "1",
    number: "1",
    name: "вул. Чорноморського козацтва — завод Центроліт",
    type: "tram",
    status: "active",
    length_km: 34.5,
    lengthDir1Km: 17.2,
    lengthDir2Km: 17.2,
    default_speed_kmh: 20.7,
    round_trip_min: 110,
    t_dir0_min: 50,
    t_dir1_min: 50,
    layover_min: 10,
    color: "#3B82F6",
    description: "Магістральна лінія до промислового вузла Центроліт",
    segments: []
  },
  {
    id: "5",
    number: "5",
    name: "Автовокзал — Аркадія",
    type: "tram",
    status: "active",
    length_km: 17.6,
    lengthDir1Km: 8.8,
    lengthDir2Km: 8.8,
    default_speed_kmh: 14.7,
    round_trip_min: 80,
    t_dir0_min: 36,
    t_dir1_min: 36,
    layover_min: 8,
    color: "#16A34A",
    description: "Зв'язок Аркадії, Французького бульвару, Привозу та Автовокзалу",
    segments: []
  },
  {
    id: "6",
    number: "6",
    name: "вул. Чорноморського козацтва — Лузанівка",
    type: "tram",
    status: "active",
    length_km: 15.5,
    lengthDir1Km: 7.7,
    lengthDir2Km: 7.7,
    default_speed_kmh: 19.4,
    round_trip_min: 54,
    t_dir0_min: 24,
    t_dir1_min: 24,
    layover_min: 6,
    color: "#06B6D4",
    description: "Скорочений маршрут Пересипського напрямку до Лузанівки",
    segments: []
  },
  {
    id: "7",
    number: "7",
    name: "вул. Паустовського — 11-та ст. Люстдорфської дороги",
    type: "tram",
    status: "active",
    length_km: 58.8,
    lengthDir1Km: 29.4,
    lengthDir2Km: 29.4,
    default_speed_kmh: 20.0,
    round_trip_min: 190,
    t_dir0_min: 88,
    t_dir1_min: 88,
    layover_min: 14,
    color: "#2563EB",
    description: "Магістральний швидкісний маршрут «Північ-Південь» через Пересипський міст та Старосінну площу",
    segments: []
  },
  {
    id: "10",
    number: "10",
    name: "вул. Іцхака Рабіна — пл. Тираспольська",
    type: "tram",
    status: "active",
    length_km: 16.0,
    lengthDir1Km: 8.0,
    lengthDir2Km: 8.0,
    default_speed_kmh: 15.0,
    round_trip_min: 72,
    t_dir0_min: 32,
    t_dir1_min: 32,
    layover_min: 8,
    color: "#D97706",
    description: "Зв'язок спального району Черемушки з центром міста",
    segments: []
  },
  {
    id: "11",
    number: "11",
    name: "Залізничний вокзал — пл. Олексіївська",
    type: "tram",
    status: "active",
    length_km: 5.6,
    lengthDir1Km: 2.8,
    lengthDir2Km: 2.8,
    default_speed_kmh: 12.0,
    round_trip_min: 34,
    t_dir0_min: 14,
    t_dir1_min: 14,
    layover_min: 6,
    color: "#8B5CF6",
    description: "Зв'язок Залізничного вокзалу зі станцією Одеса-Товарна",
    segments: []
  },
  {
    id: "12",
    number: "12",
    name: "Херсонський сквер — Слобідський ринок",
    type: "tram",
    status: "active",
    length_km: 7.6,
    lengthDir1Km: 3.8,
    lengthDir2Km: 3.8,
    default_speed_kmh: 12.7,
    round_trip_min: 42,
    t_dir0_min: 18,
    t_dir1_min: 18,
    layover_min: 6,
    color: "#EC4899",
    description: "Зв'язок району Слобідки з Пересипом через узвіз Маринеска",
    segments: []
  },
  {
    id: "13",
    number: "13",
    name: "пл. Старосінна — ж/м Шкільний",
    type: "tram",
    status: "active",
    length_km: 16.2,
    lengthDir1Km: 8.1,
    lengthDir2Km: 8.1,
    default_speed_kmh: 15.2,
    round_trip_min: 72,
    t_dir0_min: 32,
    t_dir1_min: 32,
    layover_min: 8,
    color: "#14B8A6",
    description: "Трамвайний маршрут Таїровського напрямку через Люстдорфську дорогу",
    segments: []
  },
  {
    id: "15",
    number: "15",
    name: "пл. Олексіївська — Слобідський ринок",
    type: "tram",
    status: "active",
    length_km: 15.8,
    lengthDir1Km: 7.9,
    lengthDir2Km: 7.9,
    default_speed_kmh: 14.8,
    round_trip_min: 72,
    t_dir0_min: 32,
    t_dir1_min: 32,
    layover_min: 8,
    color: "#F97316",
    description: "Маршрут через Молдаванку та Слобідку до міських лікарень",
    segments: []
  },
  {
    id: "17",
    number: "17",
    name: "Куликове поле — 11-та ст. Великого Фонтану",
    type: "tram",
    status: "active",
    length_km: 13.4,
    lengthDir1Km: 6.7,
    lengthDir2Km: 6.7,
    default_speed_kmh: 15.5,
    round_trip_min: 60,
    t_dir0_min: 26,
    t_dir1_min: 26,
    layover_min: 8,
    color: "#F59E0B",
    description: "Скорочений маршрут лінії Фонтану до кільця 11 ст. Великого Фонтану",
    segments: []
  },
  {
    id: "18",
    number: "18",
    name: "Куликове поле — 16-та ст. Великого Фонтану",
    type: "tram",
    status: "active",
    length_km: 25.4,
    lengthDir1Km: 12.7,
    lengthDir2Km: 12.7,
    default_speed_kmh: 18.1,
    round_trip_min: 92,
    t_dir0_min: 42,
    t_dir1_min: 42,
    layover_min: 8,
    color: "#DC2626",
    description: "Основна магістраль Великого Фонтану (ізольована виділена лінія)",
    segments: []
  },
  {
    id: "20",
    number: "20",
    name: "Херсонський сквер — Хаджибейський лиман",
    type: "tram",
    status: "active",
    length_km: 14.7,
    lengthDir1Km: 7.3,
    lengthDir2Km: 7.3,
    default_speed_kmh: 17.6,
    round_trip_min: 58,
    t_dir0_min: 25,
    t_dir1_min: 25,
    layover_min: 8,
    color: "#84CC16",
    description: "Історичний рекреаційний маршрут «Камишовий трамвай»",
    segments: []
  },
  {
    id: "21",
    number: "21",
    name: "пл. Тираспольська — станція Застава ІІ",
    type: "tram",
    status: "active",
    length_km: 9.6,
    lengthDir1Km: 4.8,
    lengthDir2Km: 4.8,
    default_speed_kmh: 13.1,
    round_trip_min: 50,
    t_dir0_min: 22,
    t_dir1_min: 22,
    layover_min: 6,
    color: "#6366F1",
    description: "Сполучення центру міста з промисловою зоною Застава-2",
    segments: []
  },
  {
    id: "26",
    number: "26",
    name: "пл. Старосінна — 11-а ст. Люстдорфської дороги",
    type: "tram",
    status: "active",
    length_km: 22.3,
    lengthDir1Km: 11.1,
    lengthDir2Km: 11.1,
    default_speed_kmh: 17.6,
    round_trip_min: 84,
    t_dir0_min: 38,
    t_dir1_min: 38,
    layover_min: 8,
    color: "#A855F7",
    description: "Південна магістраль Київського району до пл. Старосінної",
    segments: []
  },
  {
    id: "27",
    number: "27",
    name: "11-а ст. Люстдорфської дороги — Рибний порт",
    type: "tram",
    status: "active",
    length_km: 14.7,
    lengthDir1Km: 7.35,
    lengthDir2Km: 7.35,
    default_speed_kmh: 16.0,
    round_trip_min: 56,
    t_dir0_min: 25,
    t_dir1_min: 25,
    layover_min: 6,
    color: "#0EA5E9",
    description: "Приміська гілка від 11-ї ст. Люстдорфської дороги до Іллічівської переправи (Рибного порту)",
    segments: []
  },
  {
    id: "28",
    number: "28",
    name: "вул. Пастера — Парк ім. Тараса Шевченка",
    type: "tram",
    status: "active",
    length_km: 11.5,
    lengthDir1Km: 5.7,
    lengthDir2Km: 5.7,
    default_speed_kmh: 13.3,
    round_trip_min: 60,
    t_dir0_min: 26,
    t_dir1_min: 26,
    layover_min: 8,
    color: "#9333EA",
    description: "Кільцевий центральний маршрут через вул. Леонтовича та Тираспольську площу",
    segments: []
  },

  // --- ТРОЛЕЙБУСИ ---
  {
    id: "Tr2",
    number: "2",
    name: "Парк ім. Тараса Шевченка — вул. Новосельського",
    type: "trolleybus",
    status: "active",
    length_km: 11.3,
    lengthDir1Km: 5.6,
    lengthDir2Km: 5.6,
    default_speed_kmh: 14.1,
    round_trip_min: 56,
    t_dir0_min: 24,
    t_dir1_min: 24,
    layover_min: 8,
    color: "#059669",
    description: "Центральний маршрут від парку Шевченка до вул. Новосельського",
    segments: []
  },
  {
    id: "Tr3",
    number: "3",
    name: "станція Застава I — Парк ім. Тараса Шевченка",
    type: "trolleybus",
    status: "active",
    length_km: 17.6,
    lengthDir1Km: 8.8,
    lengthDir2Km: 8.8,
    default_speed_kmh: 15.5,
    round_trip_min: 76,
    t_dir0_min: 34,
    t_dir1_min: 34,
    layover_min: 8,
    color: "#0284C7",
    description: "Тролейбусна лінія з району Застава-1 через центр міста",
    segments: []
  },
  {
    id: "Tr7",
    number: "7",
    name: "вул. Архітекторська — вул. Новосельського",
    type: "trolleybus",
    status: "active",
    length_km: 37.5,
    lengthDir1Km: 18.7,
    lengthDir2Km: 18.7,
    default_speed_kmh: 17.3,
    round_trip_min: 140,
    t_dir0_min: 65,
    t_dir1_min: 65,
    layover_min: 10,
    color: "#4F46E5",
    description: "Магістральний тролейбус Київського району (Таїрова) до Центру",
    segments: []
  },
  {
    id: "Tr8",
    number: "8",
    name: "Суперфосфатний завод — Залізничний вокзал",
    type: "trolleybus",
    status: "active",
    length_km: 17.7,
    lengthDir1Km: 8.8,
    lengthDir2Km: 8.8,
    default_speed_kmh: 16.6,
    round_trip_min: 72,
    t_dir0_min: 32,
    t_dir1_min: 32,
    layover_min: 8,
    color: "#EA580C",
    description: "Тролейбусна лінія через вул. Космонавтів та Адміральський проспект",
    segments: []
  },
  {
    id: "Tr9",
    number: "9",
    name: "вул. Інглезі — вул. Рішельєвська",
    type: "trolleybus",
    status: "active",
    length_km: 23.5,
    lengthDir1Km: 11.7,
    lengthDir2Km: 11.7,
    default_speed_kmh: 16.8,
    round_trip_min: 92,
    t_dir0_min: 42,
    t_dir1_min: 42,
    layover_min: 8,
    color: "#0891B2",
    description: "Тролейбусне сполучення Черемушок з центром міста",
    segments: []
  },
  {
    id: "Tr10",
    number: "10",
    name: "вул. Інглезі — вул. Приморська",
    type: "trolleybus",
    status: "active",
    length_km: 31.1,
    lengthDir1Km: 15.5,
    lengthDir2Km: 15.5,
    default_speed_kmh: 17.3,
    round_trip_min: 118,
    t_dir0_min: 54,
    t_dir1_min: 54,
    layover_min: 10,
    color: "#D97706",
    description: "Швидкісний тролейбусний діагональний маршрут Черемушки — Пересип",
    segments: []
  },
  {
    id: "Tr12",
    number: "12",
    name: "вул. Архітекторська — вул. Центральний Аеропорт",
    type: "trolleybus",
    status: "active",
    length_km: 23.4,
    lengthDir1Km: 11.7,
    lengthDir2Km: 11.7,
    default_speed_kmh: 16.7,
    round_trip_min: 92,
    t_dir0_min: 42,
    t_dir1_min: 42,
    layover_min: 8,
    color: "#7C3AED",
    description: "Тролейбусний маршрут між Таїрова та Міжнародним Аеропортом Одеса",
    segments: []
  }
]
