"""Add Schedule model and link to StaticDuty

Revision ID: 936663fe2bac
Revises: 
Create Date: 2026-08-13 15:49:50.608850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '936663fe2bac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('active_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='schedulestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_id'), 'schedules', ['id'], unique=False)
    op.create_table('static_duties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('service_id', sa.Enum('WORKDAY', 'WEEKEND', 'HOLIDAY', name='serviceday'), nullable=False),
    sa.Column('duty_number', sa.String(), nullable=False),
    sa.Column('duty_type', sa.Enum('SINGLE', 'DOUBLE', 'PEAK', 'SPLIT', name='dutytype'), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_static_duties_id'), 'static_duties', ['id'], unique=False)
    op.create_table('static_shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duty_id', sa.Integer(), nullable=False),
    sa.Column('shift_sequence', sa.Integer(), nullable=False),
    sa.Column('has_break', sa.Boolean(), nullable=True),
    sa.Column('break_start_time', sa.Time(), nullable=True),
    sa.Column('break_duration_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['duty_id'], ['static_duties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_static_shifts_id'), 'static_shifts', ['id'], unique=False)
    op.create_table('static_trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('trip_sequence', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('FORWARD', 'BACKWARD', 'PULL_OUT', 'PULL_IN', name='tripdirection'), nullable=False),
    sa.Column('smoothing_state', sa.String(), nullable=True),
    sa.Column('smoothing_delta', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['shift_id'], ['static_shifts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_static_trips_id'), 'static_trips', ['id'], unique=False)
    op.create_table('static_stop_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.String(), nullable=False),
    sa.Column('stop_sequence', sa.Integer(), nullable=False),
    sa.Column('arrival_time', sa.Time(), nullable=False),
    sa.Column('departure_time', sa.Time(), nullable=False),
    sa.Column('is_break_location', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['stop_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['static_trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_static_stop_times_id'), 'static_stop_times', ['id'], unique=False)
    op.add_column('routes', sa.Column('color', sa.String(), nullable=True))
    op.add_column('stations', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('stations', sa.Column('lon', sa.Float(), nullable=True))
    op.add_column('stations', sa.Column('is_dispatch_station', sa.Boolean(), nullable=True))
    op.add_column('stations', sa.Column('break_capacity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stations', 'break_capacity')
    op.drop_column('stations', 'is_dispatch_station')
    op.drop_column('stations', 'lon')
    op.drop_column('stations', 'lat')
    op.drop_column('routes', 'color')
    op.drop_index(op.f('ix_static_stop_times_id'), table_name='static_stop_times')
    op.drop_table('static_stop_times')
    op.drop_index(op.f('ix_static_trips_id'), table_name='static_trips')
    op.drop_table('static_trips')
    op.drop_index(op.f('ix_static_shifts_id'), table_name='static_shifts')
    op.drop_table('static_shifts')
    op.drop_index(op.f('ix_static_duties_id'), table_name='static_duties')
    op.drop_table('static_duties')
    op.drop_index(op.f('ix_schedules_id'), table_name='schedules')
    op.drop_table('schedules')
    # ### end Alembic commands ###
