"""add_dispatchers_table

Revision ID: b43700bba7cc
Revises: dd60fbd53b94
Create Date: 2026-08-15 14:51:38.262158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b43700bba7cc'
down_revision: Union[str, Sequence[str], None] = 'dd60fbd53b94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispatchers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dispatchers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dispatchers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatchers_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispatchers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dispatchers_username'))
        batch_op.drop_index(batch_op.f('ix_dispatchers_id'))

    op.drop_table('dispatchers')
    # ### end Alembic commands ###
