"""initial_schema

Revision ID: dd60fbd53b94
Revises: 
Create Date: 2026-08-15 12:12:29.304088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd60fbd53b94'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('break_location_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('routeId', sa.String(), nullable=True),
    sa.Column('locationId', sa.String(), nullable=True),
    sa.Column('locationName', sa.String(), nullable=True),
    sa.Column('locationType', sa.String(), nullable=True),
    sa.Column('maxCapacityVehicles', sa.Integer(), nullable=True),
    sa.Column('durationMin', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('break_location_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_break_location_configs_id'), ['id'], unique=False)

    op.create_table('depots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('prepTimeMin', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('depots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_depots_id'), ['id'], unique=False)

    op.create_table('driver_duties',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('driver_id', sa.String(), nullable=True),
    sa.Column('block_id', sa.String(), nullable=True),
    sa.Column('start_time', sa.Integer(), nullable=True),
    sa.Column('end_time', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('breaks', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('driver_duties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_driver_duties_id'), ['id'], unique=False)

    op.create_table('drivers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('current_vehicle_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drivers_id'), ['id'], unique=False)

    op.create_table('emergency_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('cause', sa.String(), nullable=True),
    sa.Column('affectedRouteIds', sa.JSON(), nullable=True),
    sa.Column('affectedStationIds', sa.JSON(), nullable=True),
    sa.Column('detourDescription', sa.String(), nullable=True),
    sa.Column('alternativeStations', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emergency_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emergency_templates_id'), ['id'], unique=False)

    op.create_table('eta_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.String(), nullable=True),
    sa.Column('station_id', sa.String(), nullable=True),
    sa.Column('estimated_arrival_time', sa.DateTime(), nullable=True),
    sa.Column('actual_arrival_time', sa.DateTime(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eta_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eta_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_eta_logs_trip_id'), ['trip_id'], unique=False)

    op.create_table('hub_nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('locationDescription', sa.String(), nullable=True),
    sa.Column('availableTracksCount', sa.Integer(), nullable=True),
    sa.Column('minHeadwayMin', sa.Integer(), nullable=True),
    sa.Column('routesConnecting', sa.JSON(), nullable=True),
    sa.Column('channels', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hub_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hub_nodes_id'), ['id'], unique=False)

    op.create_table('incident_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.String(), nullable=True),
    sa.Column('trip_id', sa.String(), nullable=True),
    sa.Column('old_vehicle_id', sa.String(), nullable=True),
    sa.Column('new_vehicle_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incident_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_logs_id'), ['id'], unique=False)

    op.create_table('route_depot_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('routeId', sa.String(), nullable=True),
    sa.Column('primaryDepotId', sa.String(), nullable=True),
    sa.Column('secondaryDepotId', sa.String(), nullable=True),
    sa.Column('defaultOutboundTime', sa.String(), nullable=True),
    sa.Column('defaultInboundTime', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('route_depot_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_route_depot_configs_id'), ['id'], unique=False)

    op.create_table('routes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('primaryTerminalId', sa.String(), nullable=True),
    sa.Column('secondaryTerminalId', sa.String(), nullable=True),
    sa.Column('lengthDir1Km', sa.Float(), nullable=True),
    sa.Column('lengthDir2Km', sa.Float(), nullable=True),
    sa.Column('stations', sa.JSON(), nullable=True),
    sa.Column('allStations', sa.JSON(), nullable=True),
    sa.Column('segments', sa.JSON(), nullable=True),
    sa.Column('activeVehiclesCount', sa.JSON(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routes_id'), ['id'], unique=False)

    op.create_table('stations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('is_dispatch_station', sa.Boolean(), nullable=True),
    sa.Column('break_capacity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stations_id'), ['id'], unique=False)

    op.create_table('trips',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trips_id'), ['id'], unique=False)

    op.create_table('vehicle_blocks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('route_id', sa.String(), nullable=True),
    sa.Column('vehicle_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('trips', sa.JSON(), nullable=True),
    sa.Column('start_time', sa.Integer(), nullable=True),
    sa.Column('end_time', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_blocks_id'), ['id'], unique=False)

    op.create_table('vehicles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('current_trip_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_id'), ['id'], unique=False)

    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('active_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='schedulestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedules_id'), ['id'], unique=False)

    op.create_table('static_duties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('service_id', sa.Enum('WORKDAY', 'WEEKEND', 'HOLIDAY', name='serviceday'), nullable=False),
    sa.Column('duty_number', sa.String(), nullable=False),
    sa.Column('duty_type', sa.Enum('SINGLE', 'DOUBLE', 'PEAK', 'SPLIT', name='dutytype'), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('static_duties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_static_duties_id'), ['id'], unique=False)

    op.create_table('static_shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duty_id', sa.Integer(), nullable=False),
    sa.Column('shift_sequence', sa.Integer(), nullable=False),
    sa.Column('has_break', sa.Boolean(), nullable=True),
    sa.Column('break_start_time', sa.Time(), nullable=True),
    sa.Column('break_duration_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['duty_id'], ['static_duties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('static_shifts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_static_shifts_id'), ['id'], unique=False)

    op.create_table('static_trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('trip_sequence', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('FORWARD', 'BACKWARD', 'PULL_OUT', 'PULL_IN', name='tripdirection'), nullable=False),
    sa.Column('smoothing_state', sa.String(), nullable=True),
    sa.Column('smoothing_delta', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['shift_id'], ['static_shifts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('static_trips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_static_trips_id'), ['id'], unique=False)

    op.create_table('static_stop_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.String(), nullable=False),
    sa.Column('stop_sequence', sa.Integer(), nullable=False),
    sa.Column('arrival_time', sa.Time(), nullable=False),
    sa.Column('departure_time', sa.Time(), nullable=False),
    sa.Column('is_break_location', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['stop_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['static_trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('static_stop_times', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_static_stop_times_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('static_stop_times', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_static_stop_times_id'))

    op.drop_table('static_stop_times')
    with op.batch_alter_table('static_trips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_static_trips_id'))

    op.drop_table('static_trips')
    with op.batch_alter_table('static_shifts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_static_shifts_id'))

    op.drop_table('static_shifts')
    with op.batch_alter_table('static_duties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_static_duties_id'))

    op.drop_table('static_duties')
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedules_id'))

    op.drop_table('schedules')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_id'))

    op.drop_table('vehicles')
    with op.batch_alter_table('vehicle_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_blocks_id'))

    op.drop_table('vehicle_blocks')
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trips_id'))

    op.drop_table('trips')
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stations_id'))

    op.drop_table('stations')
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routes_id'))

    op.drop_table('routes')
    with op.batch_alter_table('route_depot_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_route_depot_configs_id'))

    op.drop_table('route_depot_configs')
    with op.batch_alter_table('incident_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_logs_id'))

    op.drop_table('incident_logs')
    with op.batch_alter_table('hub_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hub_nodes_id'))

    op.drop_table('hub_nodes')
    with op.batch_alter_table('eta_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eta_logs_trip_id'))
        batch_op.drop_index(batch_op.f('ix_eta_logs_id'))

    op.drop_table('eta_logs')
    with op.batch_alter_table('emergency_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emergency_templates_id'))

    op.drop_table('emergency_templates')
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drivers_id'))

    op.drop_table('drivers')
    with op.batch_alter_table('driver_duties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_driver_duties_id'))

    op.drop_table('driver_duties')
    with op.batch_alter_table('depots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_depots_id'))

    op.drop_table('depots')
    with op.batch_alter_table('break_location_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_break_location_configs_id'))

    op.drop_table('break_location_configs')
    # ### end Alembic commands ###
